[en]
label = "English"
locale = "en-CA"
weight = 1
title = "Canadian Cataloguing Taskforce"

[en.menus]
[[en.menus.main]]
name = "Goals & Groups"
pageRef = "/goals/"
weight = 20

[[en.menus.main]]
name = "Get Involved & Contact"
pageRef = "/contact/"
weight = 30

[fr]
label = "Français"
locale = "fr-CA"
weight = 2
title = "Groupe de travail canadien de catalogage"

[fr.menus]
[[fr.menus.main]]
name = "Objectifs & Groupes"
pageRef = "/goals/"
weight = 20

[[fr.menus.main]]
name = "S'impliquer & Contactez-nous"
pageRef = "/contact/"
weight = 30