[[main]]
name = "About"
pageRef = "/"
weight = 10

[[en.main]]
name = "Objections Goals"
pageRef = "/goals/"
weight = 20

[[fr.main]]
name = "Objections Goals"
pageRef = "/goals/"
weight = 20

[[en.main]]
name = "Get Involved Contact"
pageRef = "/contact/"
weight = 30

[[fr.main]]
name = "Get Involved Contact"
pageRef = "/contact/"
weight = 30